@echo off
cd /d "f:\Transform to Talent Marketplace\src\app\api"

powershell -Command "(Get-Content 'admin\analytics\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\analytics\route.ts'"
powershell -Command "(Get-Content 'admin\backup\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\backup\route.ts'"
powershell -Command "(Get-Content 'admin\categories\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\categories\route.ts'"
powershell -Command "(Get-Content 'admin\colors\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route';\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\colors\route.ts'"
powershell -Command "(Get-Content 'admin\escrow\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route';\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\escrow\route.ts'"
powershell -Command "(Get-Content 'admin\logs\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\logs\route.ts'"
powershell -Command "(Get-Content 'admin\metrics\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route';\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\metrics\route.ts'"
powershell -Command "(Get-Content 'admin\offers\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\offers\route.ts'"
powershell -Command "(Get-Content 'admin\platform\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\platform\route.ts'"
powershell -Command "(Get-Content 'admin\products\categories\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\products\categories\route.ts'"
powershell -Command "(Get-Content 'admin\products\categories\[id]\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\products\categories\[id]\route.ts'"
powershell -Command "(Get-Content 'admin\products\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\products\route.ts'"
powershell -Command "(Get-Content 'admin\products\stock\bulk\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\products\stock\bulk\route.ts'"
powershell -Command "(Get-Content 'admin\products\[id]\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\products\[id]\route.ts'"
powershell -Command "(Get-Content 'admin\products\[id]\stock\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\products\[id]\stock\route.ts'"
powershell -Command "(Get-Content 'admin\security\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\security\route.ts'"
powershell -Command "(Get-Content 'admin\sellers\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\sellers\route.ts'"
powershell -Command "(Get-Content 'admin\skills\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\skills\route.ts'"
powershell -Command "(Get-Content 'admin\stats\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\stats\route.ts'"
powershell -Command "(Get-Content 'admin\theme\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\theme\route.ts'"
powershell -Command "(Get-Content 'admin\users\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\users\route.ts'"
powershell -Command "(Get-Content 'admin\users\[id]\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'admin\users\[id]\route.ts'"
powershell -Command "(Get-Content 'bids\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route';\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'bids\route.ts'"
powershell -Command "(Get-Content 'cart\clear\route.ts') -replace \"import { authOptions } from '../../auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'cart\clear\route.ts'"
powershell -Command "(Get-Content 'cart\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'cart\route.ts'"
powershell -Command "(Get-Content 'conversations\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'conversations\route.ts'"
powershell -Command "(Get-Content 'gigs\interview-criteria.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route';\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'gigs\interview-criteria.ts'"
powershell -Command "(Get-Content 'notifications\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route';\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'notifications\route.ts'"
powershell -Command "(Get-Content 'notifications\[id]\route.ts') -replace \"import { authOptions } from '../../auth/\[\.\.\.nextauth\]/route';\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'notifications\[id]\route.ts'"
powershell -Command "(Get-Content 'orders\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'orders\route.ts'"
powershell -Command "(Get-Content 'profile\education\route.ts') -replace \"import { authOptions } from '../../auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'profile\education\route.ts'"
powershell -Command "(Get-Content 'purchases\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'purchases\route.ts'"
powershell -Command "(Get-Content 'seller-applications\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'seller-applications\route.ts'"
powershell -Command "(Get-Content 'theme\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'theme\route.ts'"
powershell -Command "(Get-Content 'uploadthing\core.ts') -replace \"import { authOptions } from \`"../auth/\[\.\.\.nextauth\]/route\`";\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'uploadthing\core.ts'"
powershell -Command "(Get-Content 'user\analytics\route.ts') -replace \"import { authOptions } from '@/app/api/auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'user\analytics\route.ts'"
powershell -Command "(Get-Content 'whatsapp-order\route.ts') -replace \"import { authOptions } from '../auth/\[\.\.\.nextauth\]/route'\", \"import { authOptions } from '@/lib/auth'\" | Set-Content 'whatsapp-order\route.ts'"

echo All auth imports fixed!
pause
